version: 0.2



phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 502193727466.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t noderepo .
      - docker tag noderepo:latest 502193727466.dkr.ecr.us-east-1.amazonaws.com/noderepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 502193727466.dkr.ecr.us-east-1.amazonaws.com/noderepo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-container","imageUri":"502193727466.dkr.ecr.us-east-1.amazonaws.com/noderepo:latest"}]' 502193727466.dkr.ecr.us-east-1.amazonaws.com/noderepo:latest > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
